### ISSUE TITLE
TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by sheerun** [dthree/vorpal#163]
I get following error when running node app using vorpal with docker-compose. I use following `docker-compose.yml`:

```
version: '2'
services:
  web:
    image: node:4-slim
    volumes:
      - .:/app
    command: node /app/dist/index.js
    links:
      - db
```

`dist/index.js` is just a simple script express server with vorpal attached. It works outside of docker.
